---
apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    app: service1
spec:
  type: ClusterIP
  selector:
    app: service1
  ports:
  - protocol: TCP
    name: http
    port: 8000
    targetPort: 8000