---
apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    app: service2
spec:
  type: ClusterIP
  selector:
    app: service2
  ports:
  - protocol: TCP
    name: http
    port: 8000
    targetPort: 8000