---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: chaostoolkit
  name: chaostoolkit-rollout-v2-service2-global-settings
  labels:
    app: chaostoolkit
spec:
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: chaostoolkit
    spec:
      serviceAccountName: chaostoolkit
      restartPolicy: Never
      containers:
      - name: chaostoolkit
        image: lawouach/kubeconeu-chaostoolkit-demo-job:v1
        imagePullPolicy: Always
        args:
        - run
        - rollout-v2-service2-global-settings.json
        env:
        - name: CHAOSTOOLKIT_IN_POD
          value: "true"
        - name: PROMETHEUS_URL
          value: "http://prometheus-k8s.monitoring.svc:9090"
        - name: JAEGER_HOST
          value: "localhost"
        - name: HUMIO_INGEST_TOKEN
          value: ""
        - name: HUMIO_DATASPACE
          value: ""
        - name: COUNTER_URL
          value: "http://service1.default.svc:8000/"
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.1"
            memory: 256Mi
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        args: ["--collector.host-port=simplest-collector.default.svc:14267"]