---
kind: Service
apiVersion: v1
metadata:
  name: ingres-service
  labels:
    service: ingres-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    service: ingres-service
  sessionAffinity: None