apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlette-deployment
  labels:
    app: starlette
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starlette
  template:
    metadata:
      labels:
        app: starlette
    spec:
      containers:
      - name: starlette
        image: gtfisher/my-starlette-image:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: starlette-ingress
spec:
  selector:
    app: starlette
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer